# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

## Creating arrays


In [4]:
np

<module 'numpy' from '/home/sorhan/projects/ml-zoomcamp/venv/lib/python3.6/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [9]:
a = np.array([1, 2, 35, 7, 12])
a

array([ 1,  2, 35,  7, 12])

In [10]:
a[3] = 10

In [11]:
a

array([ 1,  2, 35, 10, 12])

In [12]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
n[1,1] = 10

In [16]:
n

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [17]:
n[2] = n[2] * 2

In [18]:
n

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [14, 16, 18]])

In [23]:
n[:, 2] = [0, 1, 2]

In [26]:
n

array([[4, 4, 4],
       [0, 0, 0],
       [0, 0, 0]])

## Randomly generated arrays


In [27]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [31]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [32]:
np.random.seed(2)
np.random.randint(low=1, high=100, size=(2,5))

array([[41, 16, 73, 23, 44],
       [83, 76,  8, 35, 50]])

## Element-wise operations


In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
b = (10 + (a * 2)) ** 2 / 100

In [35]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [40]:
a > b

array([False, False,  True,  True,  True])

In [44]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.std()

1.4142135623730951

In [48]:
n.min()

0

### Next

Linear algebra refresher